version: '3.8'
services:
  spring-boot-template:
    container_name: spring-boot-template
    build:
      context: .
      no_cache: true # but looks like it doesn't work
    depends_on:
      db:
        condition: service_started
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local